#!/bin/bash

# Source: https://github.com/mischavandenburg/dotfiles-devpod/blob/main/setup

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# TODO need to copy over my nvim, and dotfiles over
